/**
 * Exercise system enums.
 * Single source of truth for question types, interaction modes, and validation strategies.
 */

export const QuestionType = Object.freeze({
  MATH_GRAPH: 'MATH_GRAPH',
  BAR_CHART: 'BAR_CHART',
  MCQ: 'MCQ',
  CHEMISTRY_MOLECULE_BUILDER: 'CHEMISTRY_MOLECULE_BUILDER',
  CHEMISTRY_REACTION: 'CHEMISTRY_REACTION',
  MATH_MATRIX_MULTIPLICATION: 'MATH_MATRIX_MULTIPLICATION',
  MATH_COMPLEX_NUMBER: 'MATH_COMPLEX_NUMBER',
  PHYSICS_PROJECTILE: 'PHYSICS_PROJECTILE',
  MATH_VECTOR_OPERATION: 'MATH_VECTOR_OPERATION',
});

export const InteractionMode = Object.freeze({
  DISPLAY_SELECT: 'DISPLAY_SELECT',
  FUNCTION_INPUT: 'FUNCTION_INPUT',
  PARAMETER_ADJUST: 'PARAMETER_ADJUST',
  ADD_POINTS: 'ADD_POINTS',
  MOLECULE_BUILD: 'MOLECULE_BUILD',
  DRAG_DROP_MIX: 'DRAG_DROP_MIX',
  MATRIX_DRAG: 'MATRIX_DRAG',
  COMPLEX_PLANE: 'COMPLEX_PLANE',
  PROJECTILE_LAUNCH: 'PROJECTILE_LAUNCH',
  VECTOR_ADDITION: 'VECTOR_ADDITION',
  VECTOR_SUBTRACTION: 'VECTOR_SUBTRACTION',
});

export const AnswerValidationType = Object.freeze({
  EXACT_MATCH_LABEL: 'EXACT_MATCH_LABEL',
  FUNCTION_EQUIVALENCE: 'FUNCTION_EQUIVALENCE',
  NUMERIC_RANGE: 'NUMERIC_RANGE',
  POINTS_SET_MATCH: 'POINTS_SET_MATCH',
  MOLECULE_STRUCTURE_MATCH: 'MOLECULE_STRUCTURE_MATCH',
  REACTION_PRODUCT_MATCH: 'REACTION_PRODUCT_MATCH',
  MATRIX_MATCH: 'MATRIX_MATCH',
  COMPLEX_NUMBER_MATCH: 'COMPLEX_NUMBER_MATCH',
  PROJECTILE_HIT: 'PROJECTILE_HIT',
  VECTOR_MATCH: 'VECTOR_MATCH',
});

/**
 * @typedef {Object} UserQuestionSubmission
 * @property {string} questionId
 * @property {number} nextReviewTime - Timestamp in ms
 * @property {number} lastInterval - Interval in ms
 * @property {number} attempts - Total attempts
 */
